comienza la publicacion de archivos y pastie

diff --git a/bufandarosa b/bufandarosa
--- a/bufandarosa
+++ b/bufandarosa
@@ -33,21 +33,44 @@ function nombre {
 	[ "$1" == "-h" ]&& echo 'genera nombres al azar' && exit
 	pwgen -1 $[$RANDOM%6+5]
 }
-function pastie {
-	[ "$1" == "-h" ]&& echo 'envia un mensaje a un pastie al azar usando tor, ejemplo: `echo "hola" | pastie`' && exit
+function paste {
+	[ "$1" == "-h" ]&& echo 'envia un mensaje a un paste al azar usando tor, ejemplo: `echo "hola" | paste`' && exit
 	f=`mktemp`
 	cat /dev/stdin > $f
-	proxychains wgetpaste -g -v -r -n "`nombre`" \
-	-s `echo "bpaste codepad dpaste gists poundpython" | uno` \
-	$f | grep -o "https\?://[^\"']\+" | tail -n 1
+	publicar $f paste
 	borrar $f
 }
-function img {
-	# imgur
-	curl -F "file=@$1" http://imgur.com/upload | sed 's/^.*,"hash":"/http:\/\/imgur.com\//g; s/".*$//g'
-	# uploadpie
-	curl -F upload=1 -F "uploadedfile=@$1" -F expire=5 -# http://uploadpie.com/ \
+function publicar {
+	[ "$1" == "-h" ]&& echo 'envia un archivo a un servidor de archivos al azar usando tor, ejemplo: `publicar imagen.png uploadpie`' && exit
+
+	# elige una subidor al azar
+	OPCION=`echo $2 || echo "imgur uploadpie" | uno`
+	f=$1
+
+	# verificar si un gif, jpg, png tiene más de 3M subir a imgur
+
+	# excepcion si es un txt (md, markdown) o pdf
+	# cualquier archivo desconocido convertir en txt :P
+	[ ! "$(echo $f | grep "\.\(png\|gif\|jpeg\|jpg\|pdf\|txt\)$")" ] && cp $f $f.txt && f=$f.txt
+	# pdf: uploadpie
+	[ "$(echo $f | grep "\.pdf$")" ] && echo "uploadpie" | uno
+	# txt: uploadpie o paste
+	[ "$(echo $f | grep "\.txt$")" ] && echo "paste paste uploadpie" | uno
+
+	# imgur (gif, png, jpg)
+	[ "$OPCION" == "imgur" ] && proxychains curl -F "file=@$f" http://imgur.com/upload \
+	| sed 's/^.*,"hash":"/http:\/\/imgur.com\//g; s/".*$//g'
+
+	# uploadpie (3M gif, png, jpg, pdf & txt)
+	[ "$OPCION" == "uploadpie" ] && proxychains curl -F upload=1 -F "uploadedfile=@$f" -F expire=5 -# http://uploadpie.com/ \
 	| grep -o 'http://uploadpie.com/[^\" ]*' | grep http://uploadpie.com/...
+
+	[ "$OPCION" == "paste" ] && proxychains wgetpaste -g -v -r -n "`nombre`" \
+	-s `echo "bpaste codepad dpaste gists poundpython" | uno` $f \
+	| grep -o "https\?://[^\"']\+" | tail -n 1
+
+	# borra el archivo generado por bufandarosa
+	borrar "$1.txt"
 }
 function cifrar {
 	[ "$1" == "-h" ]&& echo 'cifra mensajes, ejmplo `echo "hola" | cifrar clave`' && exit
@@ -73,7 +96,7 @@ function cifrar_irc {
 	while read SALIDA; do
 		if [ "$(echo $SALIDA | grep -i '^privmsg ')" ]; then
 			A=`echo "$SALIDA" | sed 's/:.*$//g'`
-			B=`echo "$SALIDA" | sed 's/^.*://g' |  l33t ` #| cifrar "$*" -w0`
+			B=`echo "$SALIDA" | sed 's/^.*://g' | cifrar "$*" -w0`
 			echo "$A:$B"
 		else
 			echo "$SALIDA"
@@ -131,7 +154,7 @@ function ayuda {
 	echo "Bufanda Rosa"
 	echo "============"
 	echo
-	funciones="basura cifrar descarga descifrar nombre pastie tinyurl uno irc sock"
+	funciones="basura cifrar descarga descifrar nombre paste tinyurl uno irc sock"
 	for N in $funciones; do
 		echo " $N		`$N -h`"
 	done
@@ -291,7 +314,7 @@ case $MENU in
 		;;
 	esac
 	k=`clave $(pwgen -s -y -1 $[$RANDOM%10+6])`
-	MENU=`echo -e "Texto Imágen_o_Audio Imágen_al_azar_de_la_web Publicar_en_TinyURL Publicar_en_Pastie Código_QR" | opciones -t "¿En donde?" -m "¿Donde lo queres ocultar?"` || exit
+	MENU=`echo -e "Texto Imágen_o_Audio Imágen_al_azar_de_la_web Publicar_en_TinyURL Publicar_en_paste Código_QR" | opciones -t "¿En donde?" -m "¿Donde lo queres ocultar?"` || exit
 	case $MENU in
 		0 )
 		# genera el mensaje y lo muestra en base64
@@ -336,6 +359,7 @@ case $MENU in
 		echo "$ef" | esteganografia "$k" "$b"
 		xdg-open "$(pwd)/$cf"
 		echo "$(pwd)/$cf" | mostrar "Imágen con un secreto"
+		publicar "$sf" | mostrar "URL de publicación"
 		;;
 		3 )
 			# tinyurl
@@ -348,16 +372,17 @@ case $MENU in
 		;;
 		4 )
 			# genera el mensaje, lo publica y lo muestra en base64
-			echo "$ef" | cifrar "$k" | pastie | progreso | mostrar
+			echo "$ef" | cifrar "$k" | publicar paste | progreso | mostrar
 			exit
 	   	;;
 		5)
 	                # genera codigo QR
 			cd $PICTURES
 			sf=`nombre`.png
-			qrencode -o "$sf" "$(echo "$ef" | cifrar "$k" -w0)" || error "Los QR tienen espacio limitado"
+			qrencode -o "$sf" "$(echo "$ef" | cifrar "$k" -w0)" || error "Los QR tienen espacio limitado :(" && exit
 			metadatos "$sf"
 			echo "$(pwd)/$sf" | mostrar "Código QR generado"
+			publicar "$sf" | mostrar "URL de publicación"
 	;;
 	esac
 	;;
@@ -403,7 +428,7 @@ case $MENU in
 	;;
 	2 )
 		# publicacion anonima
-		mensaje | pastie | progreso | mostrar
+		mensaje | publicar paste | progreso | mostrar
 	;;
 	3 )
 		# proxy IRC cifrado - basado en el concepto de dirtirc
